### ISSUE TITLE
Returns a CompletableFuture instead of Future.

### ISSUE THREAD

**Issue by aleschenk** [skuzzle/guice-async-extension#2]
Hi, is there any chance to add the possibility to return a CompletableFuture ? It could be great.
Thanks

**Comment by skuzzle** [comment]
I have deployed the version 1.1.0-SNAPSHOT to maven central which supports this. Would you mind testing your actual use-case to tell me whether this feature is beneficial for you? `CompletableFuture` return types are handled just like `Future` return types:
```
@Async
public CompletableFuture<Integer> compute(int n) {
    final int result = doActualCompute();
    return Futures.delegateCompletable(result);
}
```

You might need to enable Snapshot repositories in your `pom.xml` first.

**Comment by aleschenk** [comment]
Amazing!!. Thanks you so much. It's working as expected.

Great Project !

**Comment by skuzzle** [comment]
Nice to hear. I'll make a non-snapshot release these days.

**Comment by skuzzle** [comment]
FYI: 1.1.0 is released now
