### ISSUE TITLE
Please update cron-utils dependency

### ISSUE THREAD

**Issue by bgooren** [skuzzle/guice-async-extension#4]
Hi!

We're getting a stack trace logged when we add scheduled methods which have comma-separated fields (e.g. "0 0,30 * ? * *").

This was fixed in cron-utils 5.0.5 (see https://github.com/jmrozanec/cron-utils/issues/125).

Can you please update the cron-utils dependency? The 5.0.0 dependency is from august 2016 in any case, which is quite old. They are at version 8.0.0 already.

**Comment by skuzzle** [comment]
That sounds reasonable. Would you mind testing a current snapshot build in your application? I've just deployed the latest build with upgraded cron-utils dependency as `1.2.1-SNAPSHOT`

**Comment by bgooren** [comment]
Sure! Will let you know the results. Thank you!

// Bas

Verstuurd vanaf mijn iPhone

Op 19 dec. 2018 om 07:45 heeft Simon Taddiken <notifications@github.com>
het volgende geschreven:

That sounds reasonable. Would you mind testing a current snapshot build in
your application? I've just deployed the latest build with upgraded
cron-utils dependency as 1.2.1-SNAPSHOT

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/skuzzle/guice-async-extension/issues/4#issuecomment-448487443>,
or mute the thread

**Comment by bgooren** [comment]
```1.2.1-SNAPSHOT``` works fine for me 👍 

Please note it fixes another bug we encountered: cron-utils 5.0.0 contains a bug where executions on the last day of the month are skipped:
https://github.com/jmrozanec/cron-utils/issues/117

When do you expect to make a new release? Ideally we have one before the end of the month so we don't run into the cron-utils issue mentioned above.

Thanks!

**Comment by skuzzle** [comment]
You can expect the release either wthin the next few hours or at least
within the next days.

Sebastian Gooren <notifications@github.com> schrieb am Do., 20. Dez. 2018,
16:32:

**Comment by bgooren** [comment]
Much appreciated 👍

**Comment by skuzzle** [comment]
Released as `1.2.1`
